stages:
  data_ingestion:
    cmd: python src/pipeline/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - artifacts/data_ingestion/raw_data/archive.zip
    outs:
      - artifacts/data_ingestion/ingested_data

  data_validation:
    cmd: python src/pipeline/data_validation.py
    deps:
      - src/components/data_validation.py
      - artifacts/data_ingestion/ingested_data
    outs:
      - artifacts/data_validation/clean_data/final_ratings.csv
      - artifacts/data_validation/serialized_data/final_ratings.pkl

  data_transformation:
    cmd: python src/pipeline/data_transformation.py
    deps:
      - src/components/data_transformation.py
      - artifacts/data_validation/serialized_data/final_ratings.pkl
    outs:
      - artifacts/data_transformation/transformed_data/book_names.pkl
      - artifacts/data_transformation/transformed_data/book_pivot.pkl
      - artifacts/data_transformation/transformed_data/final_ratings.pkl
      - artifacts/data_transformation/transformed_data/transformed_data.pkl

  model_trainer:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/components/model_trainer.py
      - artifacts/data_transformation/transformed_data
    outs:
      - artifacts/model_trainer/model.pkl
