artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  data_ingestion_dir: data_ingestion
  dataset_download_url: https://github.com/ArpitKadam/Book-Recommender-App/raw/refs/heads/main/research/archive.zip
  raw_data_dir: raw_data
  ingested_data_dir: ingested_data

data_validation_config:
  data_validation_dir: data_validation
  clean_data_dir: clean_data
  serialized_data_dir: serialized_data
  book_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv