artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/ArpitKadam/Book-Recommender-App/raw/refs/heads/main/research/archive.zip
  data_ingestion_dir: data_ingestion
  raw_data_dir: raw_data
  ingested_data_dir: ingested_data